### ISSUE TITLE
[Coding] Week 4: Frontend + CosmosDB

### ISSUE THREAD

**Issue by emsesc** [bitprj/Intro-To-Serverless#14]
Using the CosmosDB integration that stores emotion data created in #10, add a feature to the frontend that allows users to see how many people were "happy" that day, or how many were "sad."

**Comment by emsesc** [comment]
@FifiTeklemedhin Feel free to make the feature something else. Like: `Welcome! You're joining 10 other people who were happy.` Anything that incorporates the data is perfectly fine.

**Comment by FifiTeklemedhin** [comment]
@emsesc where is the code from issue 10 stored? I don't want to have to code to start this issue, if possible

**Comment by emsesc** [comment]
@FifiTeklemedhin I believe @thearchitectsnotebook has it!

**Comment by FifiTeklemedhin** [comment]
ok, thank you!
