### ISSUE TITLE
Week 2 Issues

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#162]
Week 2 Step 2 
- [x] Checklist ` Parse an image from an HTTP request using parse-multipart` isn't clear. What does parse an image mean? You mean save it as a variable?
- [x]  Return the image encoded in base64 in the body <- specifiy that its an azure function
- [x] 📦 Installing parse-multipart <- this section doesn't have any info around how to initialize the npm init -y thing (This should be done in the vscode, not portal)
- [x] Test your work should come directly after checklist

**Comment by emsesc** [comment]
> * Installing parse-multipart <- this section doesn't have any info around how to initialize the npm init -y thing (This should be done in the vscode, not portal)

They should already know how to install npm packages (it was covered in week 1)
