### ISSUE TITLE
Week 2 Livestream (Cole) Feedback

### ISSUE THREAD

**Issue by shreythecray** [bitprj/Intro-To-Serverless#202]
- [ ] Week 2 step 3 passed without completing function
- [ ] Not sure how to test your work in steps 3, 4
- [ ] Step 3: not sure what the Headers should be (it was in step 1 but if you took a break since then then you might have forgotten and will have to comb through the documentation to find them again)

**Comment by lazyplatypus** [comment]
//install the node-fetch pacakge
var fetch = '<CODE HERE>'
 ^ this code snippet needs to be fixed
