### ISSUE TITLE
Final Project content

### ISSUE THREAD

**Issue by emsesc** [bitprj/Intro-To-Serverless#241]
- [ ] they will need to work in a single repo (no separate repo for final project)
- [ ] everything should move on by pr (edit all the headers so it is PRmerge, and you can leave files and scripts n/a)

**Comment by shreythecray** [comment]
@emsesc for single repo is that the same as the one in which they did weeks 1-4?

**Comment by emsesc** [comment]
@shreythecray Yes! So no creating another repo in this week. ALL course materials will be in the original repo

**Comment by emsesc** [comment]
Closed by #250 and #247
