### ISSUE TITLE
Add more tasks for Week 1

### ISSUE THREAD

**Issue by ganning127** [bitprj/Intro-To-Serverless#252]
### Description
The week 1 task was relatively easier compared to the live stream, so maybe we could add more features to it:
- Checking if there was no value passed in the parameter of plaintext.
- Adding a second parameter that specifies which way to take the translation (ex. English to morse or morse to English), and then have the function translate it that way. 

### ETA:
- 1-2 hours

### Objective:
- Add the task to the counselor bot opened issue page for the top secret api
- Add code to the counselor bot to test for the new tasks added

**Comment by lazyplatypus** [comment]
@ganning127 can you break this up into better tasks - this is kinda a complex issue that should be split into clearer todos
