### ISSUE TITLE
Create a General Debugging Guide

### ISSUE THREAD

**Issue by shreythecray** [bitprj/Intro-To-Serverless#257]
### Description
-  Need a document or part of the code that helps student figure out why something isn't working including the objectives below

### Objective:
> Checklist of everything you need to do to complete this issue
- [ ] Checking to make sure that their Azure account was set up properly
- [ ] Making sure that their VS Code is linked to the right Azure account locally
- [ ] Make sure to save/autosave your code
- [ ] When in doubt (or when you make any settings changes on VS Code) close the app and open it again
- [ ] If any action on VS Code is taking longer than it should then close the app and reopen it before trying again
- [ ] If you're Azure account isn't working get a new one WITH the verification code assigned to you (xxxx-xxxx-xxxx-xxxx...)

**Comment by ganning127** [comment]
I'm not sure where this should be on the github, so I'll make a google doc and it can be added into any markdown later: https://docs.google.com/document/d/13jaQrl-LK2F2q6rS1SvEt8Ov-_klFq9zG7WsOwWP7uQ/edit?usp=sharing

**Comment by blueboxes** [comment]
It would be good to include:

- Adding extra console.log, console.error etc lines to the code
- How to add a breakpoint and step through code in VS code
- How and When to add a log point and step through code in VS code
- Find the debug log inside the azure portal a deployed function

Maybe create a new folder of documents in the repo in markdown format?

**Comment by blueboxes** [comment]
Is this also linked to https://github.com/bitprj/Intro-To-Serverless/issues/183 could these be merged?

**Comment by emsesc** [comment]
@ganning127 @blueboxes This would go in the GETTING_STARTED.md file
