### ISSUE TITLE
Week 1 Step 5 - Missing step?

### ISSUE THREAD

**Issue by blueboxes** [bitprj/Intro-To-Serverless#280]
If the secret is the Azure URL (see https://github.com/bitprj/Intro-To-Serverless/issues/279) then the updated function needs to be published for the build to work which is not currently a step.

https://github.com/bitprj/Intro-To-Serverless/blob/main/.bit/responses/1.5-Week%201%20Step%205.md

**Comment by creaturenex** [comment]
So sorry about that I've been in bed since Tuesday with a really bad cold
