### ISSUE TITLE
Minor Bug Fixes

### ISSUE THREAD

**Issue by shreythecray** [bitprj/Intro-To-Serverless#3]
- [x] I LOVE how you've organized each issue - it makes it super easy to follow as a student ♥️ emojis help navigating the issues and drop downs are a great addition!!
- [x] Week 1 Step 2: might need more context on why they need to export the function and they probably don't need to usually do that when they code
- [x] Week 1 Step 5: there is a random comma right before "📝 Review: setting up Visual Studio Code"
- [x] Week 1 Step 5: there's a lot of extra spacing - not sure if this was intentional but the formatting looks different from the other issues

**Comment by emsesc** [comment]
Step 2: https://github.com/emsesc/Intro-To-Serverless/blob/main/.bit/responses/1.2-Week%201%20Step%202.md
> Added "Why do I need to export the function" drop down
Step 5: https://github.com/emsesc/Intro-To-Serverless/blob/main/.bit/responses/1.5-Week%201%20Step%205.md
> First issue: the random comma was caused by a bug in the Github counselor bot (fixed)
> Second issue: removed unneeded `<br><br/>` in markdown

@shreythecray Thoughts? :)

**Comment by shreythecray** [comment]
Looks great!!
