### ISSUE TITLE
A Song 4 U, Week 2 Step 6

### ISSUE THREAD

**Issue by dtetreau251** [bitprj/Intro-To-Serverless#305]
### Description
- 
![Capture3](https://user-images.githubusercontent.com/57218090/124335174-196ecd00-db5f-11eb-94f2-85a9cd08b3f9.PNG)

querystring or query-string

### ETA:
> How long do you think it will take to complete this?
- 5 minutes

### Objective:
> Checklist of everything you need to do to complete this issue
- [ ] Verify [docs](https://www.npmjs.com/package/query-string/v/5.1.1)
- [ ] Take appropriate action to have the instructions say query-string or querystring

**Comment by blueboxes** [comment]
Both querystring and query-string are valid npm packages with near to identical methods. Is the other version mentioned further up so they do not match?

**Comment by dtetreau251** [comment]
When you install querystring it states in the console that it's deprecated

**Comment by blueboxes** [comment]
Ah yes I see that and the docs say the same.  Unfortunately the docs don't say why. 

It will continue to work but you are right should move to a supported alternative.

https://www.npmtrends.com/qs-vs-query-string-vs-querystring-vs-querystringify-vs-urijs-vs-url-parse

**Comment by ganning127** [comment]
@dtetreau251 I can't seem to find where `query-string` is used. Could you post a screenshot?
<img width="875" alt="Screen Shot 2021-07-09 at 2 11 00 PM" src="https://user-images.githubusercontent.com/62436772/125119715-7e767580-e0bf-11eb-85d8-cbd32cfae4c3.png">
