### ISSUE TITLE
Pair Programming API

### ISSUE THREAD

**Issue by emsesc** [bitprj/Intro-To-Serverless#307]
From @blueboxes: The API suggested in the pair programming only accepts 5 requests per hour. This caught me out as we tried in postman a few time then in the code by which time we had used them all up. Depending on how you write the fetch van be hard to spot the non 200 status reply.

**Comment by ganning127** [comment]
we can use the pokemon api instead

https://pokeapi.co/

@emsesc how does this sound?

**Comment by emsesc** [comment]
sounds good 👍

**Comment by ganning127** [comment]
https://docs.google.com/document/d/1kUW1HWsxPrpDUWRQpztDjVB35AD3MkTe18QeVryt7lI/edit?usp=sharing

@shreythecray if you could change the pair programming API for translate with azure to this that would be great
