### ISSUE TITLE
Create helper method for tests

### ISSUE THREAD

**Issue by emsesc** [bitprj/Intro-To-Serverless#313]
- [ ] Identify parts of tests that can be made into functions
- [ ] Create helper method to be imported from another JS file

Many test responses would be a lot more helpful with specific error codes. Thanks @blueboxes:
```js
    if(resp.status == 404){
        console.error(`Your function could not be found at "${uri}" check function url secret 🔍`);
        process.exit(1)
    }

    if(resp.status == 500){
        console.error("Your function has an error and could not be run 🐛");
        process.exit(1)
    }
```

Additionally, adding comparisons between expected versus received:
```js
console.log(`We got "{$result}" but expected "GenY"`)
process.exit(1)
```

**Comment by blueboxes** [comment]
You put this in a helper method that all tests call.

**Comment by emsesc** [comment]
Also create function for checking secrets #321
