### ISSUE TITLE
Week 3 Step 4 - Codename Blob + 3RR0R Handling 

### ISSUE THREAD

**Issue by dtetreau251** [bitprj/Intro-To-Serverless#317]
### Description
- The following instructions are given in this step:

```  
const connectionstring = process.env["AZURE_STORAGE_CONNECTION_STRING"];
const account = "YOUR_ACCOUNT_NAME";

```

The account name is confusing. I was unsure whether I needed to enter my azure account name, the container name, etc. 

### ETA:
> How long do you think it will take to complete this?
- 5 minutes

### Objective:
> Checklist of everything you need to do to complete this issue
- [ ] Change verbiage

**Comment by blueboxes** [comment]
The `const account = "YOUR_ACCOUNT_NAME";` is the same value as that referenced in week 3 step 5. In week 3 step 5 it is in  `  "downloadUri" : "https://<YOUR_BLOB_STORAGE_URL>.blob.core.windows.net/images/<USERNAME>.png",` which even more incorrect as the value is not a full URL.

My suggestion would be to change both to `YOUR_STORAGE_ACCOUNT_NAME` and in the first add a screenshot of where to find it in the portal.
