### ISSUE TITLE
Create BP Extension Pack for VS Code 

### ISSUE THREAD

**Issue by dtetreau251** [bitprj/Intro-To-Serverless#320]
### Description
- Create an extension pack to help students with setting up their VS Code 

### ETA:
> How long do you think it will take to complete this?
- 30 minutes

### Objective:
> Checklist of everything you need to do to complete this issue
- [ ] Read [this](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) documentation
- [ ] Read [this](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) documentation
- [ ] Select extensions which need to be included
- [ ] Update md file to have students download the extension pack after they install VS Code
- [ ] Ping visual studio code on twitter and have them feature the extension pack

**Comment by blueboxes** [comment]
What sort of things were you thinking of  including to check?

**Comment by dtetreau251** [comment]
@blueboxes ESLint/TSLint, Code Spell Checker, Prettier, Path Intellisense, NPM, Beautify, Azure Functions, Azure Storage, Azure Account

**Comment by dtetreau251** [comment]
In order to create this extension pack I'll need permission to create a publisher id on behalf of the organization. 

@lazyplatypus

**Comment by marcduiker** [comment]
> @blueboxes ESLint/TSLint, Code Spell Checker, Prettier, Path Intellisense, NPM, Beautify, Azure Functions, Azure Storage, Azure Account

If these are all VSCode extensions, a `.vscode/extension.json` file that contains recommendations would be enough. When students clone the repo and open the folder in VSCode they'll be notified by VSCode to install the recommended extensions. See https://tattoocoder.com/recommending-vscode-extensions-within-your-open-source-projects/

Here's an example of an extensions.json for one of my projects:
```json
{
  "recommendations": [
    "ms-azuretools.vscode-azurefunctions",
    "ms-dotnettools.csharp",
    "streetsidesoftware.code-spell-checker",
    "davidanson.vscode-markdownlint",
    "blackmist.linkcheckmd",
    "vsls-contrib.codetour"
  ]
}

```

**Comment by blueboxes** [comment]
I did not know you could do that, I think it is a much cleaner solution.

**Comment by dtetreau251** [comment]
Nice!


Sent from Yahoo Mail for iPhone


On Monday, July 12, 2021, 3:13 AM, Marc Duiker ***@***.***> wrote:





@blueboxes ESLint/TSLint, Code Spell Checker, Prettier, Path Intellisense, NPM, Beautify, Azure Functions, Azure Storage, Azure Account


If these are all VSCode extensions, a .vscode/extension.json file that contains recommendations would be enough. When students clone the repo and open the folder in VSCode they'll be notified by VSCode to install the recommended extensions. See https://tattoocoder.com/recommending-vscode-extensions-within-your-open-source-projects/

Here's an example of an extensions.json for one of my projects:
{
  "recommendations": [
    "ms-azuretools.vscode-azurefunctions",
    "ms-dotnettools.csharp",
    "streetsidesoftware.code-spell-checker",
    "davidanson.vscode-markdownlint",
    "blackmist.linkcheckmd",
    "vsls-contrib.codetour"
  ]
}

**Comment by dtetreau251** [comment]
I cant add a .vscode code folder from github and i dont have access rights if i try to push from a cloned down repo
