### ISSUE TITLE
Setup Check Script that  checks what's installed and shows a list of ✅ and ❌

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#329]
On a fresh VM I needed to install Git and Curl first but after that, it mostly worked.

I will approve on the fact it may work for some people but think may need work overtime. Maybe we should have a separate script that just checks what's installed and shows a list of ✅ and ❌

![Tested](https://user-images.githubusercontent.com/985852/124951945-ba500300-e00b-11eb-8c23-9599f5b29fc6.png)

_Originally posted by @blueboxes in https://github.com/bitprj/Intro-To-Serverless/issues/318#issuecomment-876547933_

**Comment by dtetreau251** [comment]
I updated the [md](https://github.com/bitprj/Intro-To-Serverless/pull/319/files#diff-d0243df16bd9ebcc544cb26394cf6ec5cc2be67bdca0a44c51457c0baf94b1c8) file to better explain what needs to be installed prior to installing the script. Could we merge these for now and maybe follow up with an amended setup script?

**Comment by lazyplatypus** [comment]
of course!

**Comment by dtetreau251** [comment]
I am requesting to close this out based on it being solved by directions I gave in the gettingstarting.md to make sure prerequisite tools were installed.
