### ISSUE TITLE
[Feature] Create a premade folder with every single project that will be made by the student, with READMEs

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#335]
### Proposal
Create a premade folder with every single project that will be made by the student with READMEs. This would prevent students from misnaming the directories, and provide a nice preview of each app they will make in the README. 

- [ ] HackerVoice
- [ ] TwoCatz
- [ ] Top Secret
- [ ] Emotional Gifs
- [ ] Song4u
- [ ] Bunnimage
- [ ] Deep Secrets

### References
https://github.com/microsoft/ML-For-Beginners/tree/main/5-Clustering/1-Visualize

**Comment by emsesc** [comment]
Needs to be tested with Azure Functions plugin - not sure how it would react with an already existing folder name with the same name as a new function

**Comment by blueboxes** [comment]
@emsesc  you are correct if the folder exists you can not select to create new function in a folder of the same name.

![image](https://user-images.githubusercontent.com/985852/125031388-7ea54f80-e084-11eb-9f65-2a00bbf7db53.png)

**Comment by emsesc** [comment]
@lazyplatypus In that case should we close this issue or do you have other ideas?
