### ISSUE TITLE
[Content Bug] Storing files and things with DB WEEK 3, STEP 1

### ISSUE THREAD

**Issue by dtetreau251** [bitprj/Intro-To-Serverless#338]
The instructions for this step should specify anonymous or  function. Anonymous was demonstrated in the [video](https://www.notion.so/Week-3-ffc40873b5f042cfab6ea603ea4e1091). It was mentioned that the response would be different in Postman if function was used. However, this was not clear. 

**Identify Steps:**
* Step 1

**Week:**
3

## Describe the Issue

![WEEK 3 STEP 1](https://user-images.githubusercontent.com/57218090/125019811-44fd2600-e03d-11eb-99f0-1c019dca1f9c.PNG)

## Proposed Fix

Specify function or anonymous

**Comment by blueboxes** [comment]
The response should not be different based on the auth method as far as I know, though agree to specify the auth type would be good.

**Comment by dtetreau251** [comment]
I think the biggest thing was that students have to upload an image to blob storage from Postman in a later step. This works differently depending on the auth and could lead to confusion.
