### ISSUE TITLE
[Content Bug] Remove jQuery

### ISSUE THREAD

**Issue by emsesc** [bitprj/Intro-To-Serverless#376]
**Identify Steps:**
* Step 1
* Step 2
* Step 3
* Step 4

**Week:** 4

## Describe the Issue

From @blueboxes:
> jQuery was designed to solve a problem that all browsers worked differently and were not everygreen updated. This is no longer the case and everything in jQuery can be done in vanilla js.

There is a modern lightweight jQuery that does not support the weird old browsers but this is pointless. So yes in short I would not intro jQuery.

## Proposed Fix

Remove jQuery instructions and instead utilize [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent). Also, update sample solutions.

**Comment by blueboxes** [comment]
If you need to remove it from any other places see http://youmightnotneedjquery.com/ for the alternative commands

**Comment by dtetreau251** [comment]
I have PRs up for step 1 -3 where I have removed jQuery. They are in progress.

**Comment by ganning127** [comment]
@dtetreau251 Is this pretty much done? I just looked through the steps 1-4 and I can't find jquery

**Comment by dtetreau251** [comment]
Yea
