### ISSUE TITLE
[Content Bug] Week 2 Step 2 Change Wording

### ISSUE THREAD

**Issue by ganning127** [bitprj/Intro-To-Serverless#409]
Delete "new" in the first step.

**Comment by emsesc** [comment]
@ganning127 Could you explain a bit more about this issue? This is the first step in the task list of this step:
```
- [ ] Create a new branch called `emotionalgifs`
```

**Comment by ganning127** [comment]
Good point I think I actually had a brainfart when I created this issue. I think the wording is fine
