### ISSUE TITLE
[FINAL PROJECT] Add blog template

### ISSUE THREAD

**Issue by emsesc** [bitprj/Intro-To-Serverless#50]
Add a blog template ex: `insert your bio here` to standardize blogs and how to explain code.

**Comment by emsesc** [comment]
Make this a [PR template](https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters)

**Comment by lazyplatypus** [comment]
What are the thoughts on the sections being 
- about me
- the premise behind the project
- flow chart
- How I built it
- Challenges
- Thanks

**Comment by emsesc** [comment]
- About me
- Premise behind project
- Flow chart
- Tools used
- Step by step (with code snippets)
- Challenges + lessons learned
- Thank you's
