### ISSUE TITLE
Week 1 Step 5 Suggestion

### ISSUE THREAD

**Issue by shreythecray** [bitprj/Intro-To-Serverless#57]
- [x] Task heading size is smaller than previous tasks
- [x] .bit/.progress file changes every step, need to remind students to git pull before pushing their code

~~- [ ] Need to change base64 testing link to https://base64.guru/converter/decode/file~~

**Comment by emsesc** [comment]
@shreythecray why does the link need to be changed? Students are decoding base64 into a cat image.

**Comment by shreythecray** [comment]
@emsesc when I tried to use the previous link it didn't work and it instead gave me an error telling me to use https://base64.guru/converter/decode/file this page. I just checked again and the original link is working, so I'm going to close this issue.
