### ISSUE TITLE
Week 1 Step 6: Testing Problem

### ISSUE THREAD

**Issue by shreythecray** [bitprj/Intro-To-Serverless#69]
- [ ] Should explain how to re-run jobs on an action if it fails (when retrying)
- [ ] If I try to go to the next step without adding the secret (e.g. if I forget) then I can't actually tell why I can't move forward:
<img width="1431" alt="Screen Shot 2021-04-26 at 3 18 34 AM" src="https://user-images.githubusercontent.com/28051494/116067633-2d1d2500-a63e-11eb-904e-f7d3305ac70a.png">

**Comment by emsesc** [comment]
@shreythecray 
> If I try to go to the next step without adding the secret (e.g. if I forget) then I can't actually tell why I can't move forward:

It'll tell you the problem if you click on the "build." For explaining how to fix the errors, should we add an MD file in the repo?

**Comment by lazyplatypus** [comment]
yes

**Comment by emsesc** [comment]
Issue resolved
