### ISSUE TITLE
Create Week 8 Curriculum - How to Create a lightning talk

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#73]
- [ ] What makes a great lightning talk
- [ ] Creating an outline of slides

.... helppppp

**Comment by emsesc** [comment]
- [ ] What makes a great lightning talk
- [ ] Creating an outline of slides
- [ ] How to give a presentation (keep people engaged)
- [ ] Don't put a bunch of words on your slides! Use gifs!
- [ ] Slide design
- [ ] Content needed for lightning talk
