### ISSUE TITLE
Refactor Week 3 content

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#83]
Because we are going to move week 3 step 1/2/3 to week2, we are going to have to add content to better teach students on how to use cosmos db. 

We should create a new azure function to store images sent with twilio into a cosmosdb through azure functions. The step by step tutorial on how to 

1) Create the nodejs app
2) Connect /setup cosmosdb 
3) remind work on twilio api 

can lead students to gain the skills necessary to add cosmosdb to their og project.

**Comment by emsesc** [comment]
## The *Deep Secrets* API
Text a number (twilio) with a secret message --> Azure Function will store in CosmosDB --> Azure Function selects random confession --> Twilio replies back

@lazyplatypus Was this something you were thinking of? What about the "nodejs" part - were you just referring to the azure funciton?

**Comment by emsesc** [comment]
```js
const querystring = require('querystring');
const CosmosClient = require("@azure/cosmos").CosmosClient;
// npm install @azure/cosmos

const config = {
  endpoint: process.env.ENDPOINT,
  key: process.env.KEY,
  databaseId: "SecretStorer",
  containerId: "secrets",
  partitionKey: {kind: "Hash", paths: ["/secrets"]}
};

async function create(client, databaseId, containerId) {
   const { database } = await client.databases.createIfNotExists({
      id: config.databaseId
   });

   const { container } = await client
      .database(config.databaseId)
      .containers.createIfNotExists(
         { id: config.containerId, key: config.partitionKey },
         { offerThroughput: 400 }
      );
   }

async function createDocument(newItem) {
    var { endpoint, key, databaseId, containerId } = config;
    const client = new CosmosClient({endpoint, key});
    const database = client.database(databaseId);
    const container = database.container(containerId);
    await create(client, databaseId, containerId);

    const querySpec = {
        query: "SELECT * from c"
    };

// read all items in the Items container
    const { resources: items } = await container.items
        .query(querySpec)
        .fetchAll();

    const {resource: createdItem} = await container.items.create(newItem);
    return items
}

module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    const queryObject = querystring.parse(req.body);
    message = queryObject.Body;
    let document = {"message":message}

    let items = await createDocument(document)
    context.log(items)
    var random_value = Math.floor(items.length * Math.random())

    const responseMessage = `Thanks 😊! Stored your secret "${message}". 😯 Someone confessed that: ${JSON.stringify(items[random_value].message)}`

    context.res = {
        // status: 200, /* Defaults to 200 */
        body: responseMessage
    };
}

// https://www.twilio.com/docs/sms/quickstart/node
// https://www.neilwithdata.com/azure-functions-post-body-js
```

**Comment by lazyplatypus** [comment]
Week 3
step 1. Azure Functions Takes a message as an input and store it into the cosmos db, returns the last three messages as the result. (The test function would send three different requests, and check the return of the last one. 

step 2. Azure Functions Takes a message as an input and store it into the cosmos db, returns a random result.

step 3. Text a number (twilio) with a secret message --> Azure Function will store in CosmosDB --> Azure Function selects random confession --> Twilio replies back

**Comment by emsesc** [comment]
Week 3
step 1. Azure Functions Takes a message as an input ***from POST request body*** and store it into the cosmos db, returns the ***most recent*** three messages as the result. (The test function would send three different requests, and check the return of the last one.

step 2. Azure Functions Takes a message as an input and store it into the cosmos db, returns a random result.

step 3. Text a number (twilio) with a secret message --> Azure Function will store in CosmosDB --> Azure Function selects random confession --> Twilio replies back ***technically for this all you have to do is to return it in the body***

**Comment by emsesc** [comment]
# Week 3
## Bunnimage
**Step 1**
* Set up blob storage
* Code Azure Function that takes image in as the `body` and the "code name" as the `header` and uploads to blob storage container

**Step 2**
* Code Azure Function that takes "code name" as input and returns the image download link
* Working with blob SDK

**Step 3**
* Create `upload.html` that links JS to make a call to the first Azure Function
* Create `download.html` and link JS that makes a call to the Azure function with the code name

## Deep Secrets API
**Step 4**
* Take a message from a POST request body and store it into CosmosDB
* Return a random message from the Azure Function

**Step 5**
* Take a voice message from a POST request body and store it into CosmosDB
* Receive a phone number as input and send it as a parameter
* Return a random voice message from the Azure Function

**Step 6**
* Create a frontend that allows users to record (provide HTML)
* Link JS that makes a request to the Azure function

**Step 7**
* Make the Azure Function use Twilio to call the specified phone number
* Play the random secret message
